name       : libasyncns
version    : '0.8'
release    : 5
source     :
    - http://0pointer.de/lennart/projects/libasyncns/libasyncns-0.8.tar.gz : 4f1a66e746cbe54ff3c2fbada5843df4fbbbe7481d80be003e8d11161935ab74
homepage   : http://git.0pointer.net/libasyncns.git/
license    : GPL-2.0
component  : desktop.library
summary    : Asynchronous Name Service API
description: |
    Asynchronous Name Service API
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
